SELECT
    CAR_ID,
    CC.CAR_TYPE,
    ROUND(DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100)) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS CC
INNER JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP
ON
    CC.CAR_TYPE = DP.CAR_TYPE
WHERE 
    CC.CAR_ID NOT IN (
        SELECT
            RH.CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
        WHERE
            RH.START_DATE <= '2022-11-30' AND RH.END_DATE >= '2022-11-01'
    )
AND 
    DP.DURATION_TYPE = "30일 이상"
HAVING 
    FEE >= 500000
AND
    FEE < 2000000
ORDER BY
    FEE DESC, CC.CAR_TYPE ASC, CC.CAR_ID DESC;
    
